/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 SateliteAqua.glb 
*/

import React ,{useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Aqua(props) {
  const { nodes, materials } = useGLTF('/SateliteAqua.glb');
  const aquaRef = useRef();  // Referencia para el satélite

  // Usamos useFrame para imprimir la posición del satélite
  useFrame(() => {
    if (aquaRef.current) {
      aquaRef.current.rotation.y += 0.01;  // Rotar sobre el eje Y
      console.log('Posición del satélite:', aquaRef.current.position);
    }
  });
  return (
    <group ref={aquaRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object1.geometry} material={materials.black_krinkle_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object10.geometry} material={materials['MDF Nero - Guararapis*']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object11.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object12.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object13.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object14.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object15.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object16.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object17.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object18.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object19.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object2.geometry} material={materials.black_krinkle_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object20.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object21.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object22.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object23.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object24.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object25.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object26.geometry} material={materials['AR3DMat PBR Yellow Plaster']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object27.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object28.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object29.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object3.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object30.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object33.geometry} material={materials['Material.001']} position={[13.181, 18.655, 5.286]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object34.geometry} material={materials['Material.001']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object36.geometry} material={materials['Material.001']} position={[13.181, 18.655, 5.31]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object4.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object42.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object43.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object44.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object45.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object46.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object47.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object48.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object49.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object5.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object50.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object51.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object52.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object53.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object54.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object55.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object56.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object57.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object58.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object59.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object6.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object60.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object61.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object62.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object63.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object64.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object65.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object66.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object67.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object68.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object69.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object7.geometry} material={materials['AR3DMat PBR Yellow Plaster']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object70.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object71.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object72.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object73.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object74.geometry} material={materials.foil_silver_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object75.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object76.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object77.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object78.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object79.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object8.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object80.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object81.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object82.geometry} material={materials['Procedural amber']} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object9.geometry} material={materials.tex_01_0} position={[13.181, 18.655, 5.322]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object041.geometry} material={materials['Material.001']} position={[16.299, 18.655, 5.23]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object035.geometry} material={materials['Material.001']} position={[16.279, 18.655, 5.239]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object031.geometry} material={materials['Material.001']} position={[10.077, 18.655, 5.37]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object038.geometry} material={materials['Material.001']} position={[10.065, 18.655, 5.382]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object040.geometry} material={materials['Material.001']} position={[6.962, 18.655, 5.455]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object037.geometry} material={materials['Material.001']} position={[6.962, 18.655, 5.442]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object039.geometry} material={materials['Material.001']} position={[3.858, 18.655, 5.527]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
      <mesh geometry={nodes.Object032.geometry} material={materials['Material.001']} position={[3.87, 18.655, 5.539]} rotation={[-0.003, -1.546, -Math.PI]} scale={0.122} />
    </group>
  )
}

useGLTF.preload('/SateliteAqua.glb')
